#!/bin/bash

# fail fast
set -o errexit
set -o nounset
set -o pipefail

# globals
readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(dirname $0)
readonly ARGS="$@"

main() {
  local build_dir="$1"

  cd "$build_dir" >/dev/null 2>&1
  git init >/dev/null 2>&1
  echo "Testing 1" > README
  git add README >/dev/null 2>&1
  git commit -m 'Initial commit' >/dev/null 2>&1
  git tag v0.4.0
  echo "Testing 2" > README
  git add README >/dev/null 2>&1
  git commit -m 'Add README' >/dev/null 2>&1
  cd - >/dev/null 2>&1
}

main "$@"
